app/urls.py
from django.urls import path
from .views import main,detail
app_name="app"

urlpatterns = [
    path('',main, name="main"),
    path('detail/<int:pk>/',detail, name="detail")
]

basket/urls.py
from django.urls import path
from .views import add_to_basket,get_basket


app_name="basket"



urlpatterns = [
    path('add/<int:pk>/' , add_to_basket, name='add_to_basket'),
    path('basket/' , get_basket, name='get_basket')
   
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profiles/',include('profiles.urls')),
    path('basket/',include('basket.urls')),
]
urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)  

profiles/urls.py
from django.urls import path
from .views import add_comment, signup, feedback


app_name="profiles"



urlpatterns = [
    path( 'signup/',signup, name ="signup"),
    path('comment/<int:pk>,',add_comment,name="add_comment"),
    path( 'feedback/',feedback, name ="feedback"),
]

app/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название")

    class Meta:
        verbose_name ="Категория"
        verbose_name_plural= "Категории"

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=50,verbose_name="Название")
    price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name="Цена")
    description = models.CharField(max_length=200,verbose_name="Описание")
    image=models.ImageField(upload_to="images",verbose_name="Картинка")        
    Category = models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name="Категорий")
    active = models.BooleanField(default=True,verbose_name="Активна" )
    count =models.IntegerField(verbose_name="Колличество")
    class Meta:
        verbose_name ="Товар"
        verbose_name_plural= "Товары"

    def __str__(self):
        return self.name

basket/models.py
from django.db import models
from app.models import Product
from django.contrib.auth import get_user_model

# Create your models here.
User =get_user_model()



class Basket(models.Model):
    owner =models.ForeignKey(User,related_name='baskets',on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    number = models.CharField(max_length=20)
  
class BasketProduct(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='basket_product')
    cart =models.ForeignKey(Basket,on_delete=models.CASCADE,related_name='basket_product')
      

profiles/models.py
from django.db import models

from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.db.models.fields import CharField
from app.models import Product 



class MyUserManager(BaseUserManager):

    def create_user(self, username, password):
        user = self.model(
            username=self.normalize_email(username),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password):
        user = self.create_user(username, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

    def get_by_natural_key(self, username):
        return self.get(**{self.model.USERNAME_FIELD: username})   


class MyUserModel(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=36, unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    USERNAME_FIELD = 'username'
    objects = MyUserManager()
    
    def save(self, *args, **kwargs):
        super(MyUserModel, self).save(*args, **kwargs)

class Comement(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,related_name='comments')
    text = models.CharField(max_length=200)
    title = models.CharField(max_length=20)
    user = models.ForeignKey(MyUserModel,related_name='comments', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title    

basket/forms.py
from django import forms
from django.forms import fields
from .models import Basket



class BasketForm(forms.ModelForm):
    
    class Meta:
        model = Basket
        exclude = ['owner']

profiles/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import MyUserModel,Comement
from django import forms


class SignupForm(UserCreationForm):
    class Meta:
        model = MyUserModel
        fields = ('username', 'password1','password2')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comement
        fields = ['title','text'] 

class FeedBackForm(forms.Form):
    number =forms.CharField(max_length=20)
    name = forms.CharField(max_length=20)
    text = forms.CharField(max_length=200)

app/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from .models import Category, Product
from profiles.forms import CommentForm
# Create your views here.
def main(request):
    form = CommentForm(request.user)
    products= Product.objects.all()
    category_id = request.GET.get('category')
    if category_id:
        products =products.filter(Category_id=category_id)    
    categories = Category.objects.all().order_by('name')
    return render(request,'main.html', {"categories":categories,"products": products})

def detail(request,pk):
    form = CommentForm()
    product = Product.objects.get(pk=pk)
    categories = Category.objects.all().order_by('name')
    return render(request, 'detail.html', {"categories":categories,'product': product,"form":form})


        

basket/views.py
from django.shortcuts import redirect, render
from basket.models import BasketProduct
from .basket import Cart
from app.models import Product
from .forms import BasketForm

# Create your views here.
def add_to_basket(request,pk):
    if not request.user.is_authenticated:
        return redirect("profiles:signup")
    product = Product.objects.get(pk=pk)
    cart =Cart(request)
    cart.add(product)
    return redirect("app:main")    


def get_basket(request):
    cart = Cart(request)
    product_ids = cart.get_products()
    form = BasketForm(request.POST or None)
    products = Product.objects.filter(id__in=product_ids)
    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        instance.owner = request.user
        instance.save()
        basket_products = [BasketProduct(product=product, basket=instance) for product in products]
        BasketProduct.objects.bulk_create(basket_products)
        cart.clear()
        return redirect("app:main")
    return render(request, 'basket.html', {'products': products, 'form': form})

profiles/views.py
from django.shortcuts import render,redirect

# Create your views here.
from django.contrib.auth import login, authenticate

from django.shortcuts import render, redirect
from .forms import FeedBackForm, SignupForm,CommentForm
from profiles import utils
from django.conf import settings
import telegram 

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})

def add_comment(request,pk):
    if request.method =='POST':
        form = CommentForm(request.POST)
        if form.is_valid():    
            comment =form.save(commit=False)
            comment.user =request.user
            comment.product_id = pk
            comment.save()
    return redirect('app:detail',pk=pk)

def feedback(request):
    form = FeedBackForm(None or request.POST)
    if request.method =='POST':
        if form.is_valid():
            dict = request.POST.copy()
            dict.pop("csrfmiddlewaretoken")
            message = utils.message.format(**dict)
            bot = telegram.Bot(token=settings.BOT_TOKEN)
            bot.send_message(chat_id=settings.CHAT_ID,text=message)
    return render(request,'feedback.html',{'form':form})

# def basket(request):
#     basket = True
#     if request.user.is_authenticated:
#         basket =True
#         return render(request,'app:main')
#     else:
#         return redirect('profiles:signup')    
    

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Main</title>
  </head>
  <body>
      <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'app:main' %}"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh8TDGarL6OdBsVSMx3lo03_Ag5tCI5CqQEA&usqp=CAU" style="width: 50px; height: 50px;"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  {% if request.user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="">{{request.user.username}}</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">logout</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'login' %}">login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'profiles:signup' %}">REGISTRATION</a>
                    </li>
                  {% endif %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Категории
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                     {% for category in categories %}
                      <li><a class="dropdown-item" href="{% url 'app:main' %}?category={{category.id}}">{{category.name}}</a></li>
                      {% endfor %}
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'app:main' %}">Все категории</a></li>
                    </ul>
                  </li>
                  
                </ul> 
                <a class="nav-link" href="{% url 'basket:get_basket' %}"><img src="{% static 'korzina/1.png' %}" alt="" style="width: 50px; height: 50px;""></a>
                <!-- <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form> -->
              </div>
            </div>
          </nav>
      </header>
    {% block content %}
    {% endblock %}
    <footer>
        <ul class="nav justify-content-center">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'profiles:feedback' %}">Active</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
    </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<div class ='row'>
  <div class ='col-8' style="margin-left: 15%; margin-right: 5%;">
    <div class="card mb-3">
      <img src="{{product.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{product.name}}</h5>
        <p class="card-text">{{product.description}}</p>
        <p class="card-text"><small class="text-muted">{{product.Category}}</small></p>
        <p class="card-text"><small class="text-muted">{{product.price}}</small></p>
      </div>
    </div>

  </div>
  <div class="row">
    {% for comment in product.comments.all %}
    <div class="col-12">
      <div class="card text-dark bg-light mb-3" style="max-width: 18rem; margin-left: 40%;">
        <div class="card-header">{{comment.title}}</div>
        <div class="card-body">
          <h5 class="card-title">{{comment.user.username}}</h5>
          <p class="card-text">{{comment.text}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

    {% if request.user.is_authenticated %}
      <form action="{% url 'profiles:add_comment' pk=product.pk %}"  style="margin-left:40%" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary">Создать</button>
      </form>
    {% endif %}
</div>
{% endblock %}

app/templates/main.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    {% for product in products %}
    <div class="col-4" style="margin-top: 5%; margin-bottom: 3%;">
        <div class="card" style="width: 18rem;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
            <a class="card-title" href="{% url 'app:detail' pk=product.pk %}">{{ product.name }}</a>
            <p class="card-text">{{product.description}}</p>
            <a href="{% url 'profiles:buy' %}" class="btn btn-primary">Купить</a>
            </div>
        </div>
    </div>
    {% endfor %}
        </div>
    </div>

        </div>
    </div>
</div>
{% endblock %}

basket/templates/basket.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    {% for product in products %}
    <div class="col-4" style="margin-top: 5%; margin-bottom: 3%;">
        <div class="card" style="width: 18rem;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
            <a class="card-title" href="{% url 'app:detail' pk=product.pk %}">{{ product.name }}</a>
            <p class="card-text">{{product.description}}</p>
            <a href="{% url 'basket:add_to_basket' pk=product.pk %}" class="btn btn-primary">Купить</a>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'basket:get_basket' %}"  style="margin-left:40%" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary">Оформить</button>
      </form>
        </div>
    </div>

        </div>
    </div>
</div>
{% endblock %}

profiles/templates/feedback.html
{% extends 'base.html' %}
{% block content %}
    {% if request.user.is_authenticated %}
<form style="margin-left:40%" method="POST">
    <h2>Feedback</h2>
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-primary">Отправить</button>
    
  </form>
    {% else %}
        <h3>Login or REGISTRATION</h3>
    {% endif %}
  {% endblock %}

profiles/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<section class="vh-100" style="background-color: #508bfc;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card shadow-2-strong" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
            <h2>Sign up</h2>
              <div class="layer1">
                  <form class="card card-body" method='POST'> {% csrf_token %}
                      {{ form.as_p }}
                      <br>
                      <button class="btn btn-primary" type="submit">Sign up</button>
                  </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}